services:
  - type: web # Backend: tipo web com runtime node
    name: financas-pessoais-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npx prisma migrate deploy && npm start"
    healthCheckPath: /dashboard
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: financas-pessoais-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://financas-pessoais-frontend.onrender.com

  - type: web # Frontend: O tipo DEVE ser 'web' no Blueprint
    name: financas-pessoais-frontend
    runtime: static # Mas a propriedade 'runtime' deve ser 'static'
    buildCommand: "echo \"No build command for static site\""
    staticPublishPath: ./frontend # Verifique se esta é a pasta correta
    autoDeploy: true
    envVars:
      - key: BACKEND_URL_PLACEHOLDER # Essa variável NÃO é injetada. Verifique se a substituição manual já foi feita no script.js.
        fromService: 
          name: financas-pessoais-backend
          property: host

databases:
  - name: financas-pessoais-db
    plan: free
    databaseName: financas_pessoais
    user: financas_user
