services:
  - type: web
    name: financas-pessoais-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npx prisma migrate deploy && npm start"
    healthCheckPath: /dashboard
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: financas-pessoais-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://financas-pessoais-frontend.onrender.com

  - type: web # Corrigido de 'static_site' para 'web'
    name: financas-pessoais-frontend
    runtime: static # Adicionado para indicar que é um site estático
    buildCommand: "echo \"No build command for static site\""
    staticPublishPath: ./frontend # Verifique se o caminho da pasta está correto (ou use o seu caminho original)
    autoDeploy: true
    envVars:
      - key: BACKEND_URL_PLACEHOLDER
        fromService: 
          name: financas-pessoais-backend
          type: web # <-- CORREÇÃO: Informando o tipo do serviço referenciado
          property: host

databases:
  - name: financas-pessoais-db
    plan: free
    databaseName: financas_pessoais
    user: financas_user
